---
- name: Master nodes - Inbound rules
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop: "{{ k8s_master_ports }}"
  when: "'masters' in group_names"

- name: Etcd nodes - Inbound rules
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop: "{{ k8s_etcd_ports }}"
  when: "'etcd' in group_names"

- name: Worker nodes - Inbound rules
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop: "{{ k8s_worker_ports }}"
  when: "'workers' in group_names"

- name: Enable masquerade
  firewalld:
    masquerade: yes
    permanent: yes
    immediate: yes
    state: enabled
